### ISSUE TITLE
Brickyard@4.0.0

### ISSUE THREAD

**Issue by CoderIvan** [dbjtech/brickyard-cli#2]
#### 去除对gulp的hack
 * 删除第三方工具类的hack，如del, merge-stream等，由下游自行依赖
 * 删除非第三方工具类的hack，如gulp.create_task，通过brickyard暴露，让上下游之间的接口更小更集中

#### 让build后的项目，更加独立
* 项目所依赖的node_modules放至build目录下

#### 让brickyard-cli的构建更完整
* 项目所需要的依赖由brickayrd-cli构建的时候安装，而非buildtask/install，解决build/install运行时build/install所需的依赖还未安装的矛盾

**Comment by vincentngthu** [comment]
npm和bower是buildtasks/install插件的依赖，而且只在这个插件用到

**Comment by CoderIvan** [comment]
我的描述可能有点岐义，但现在是在brickayr-cli上依赖npm的，并且无法移动至buildtask/install中进行声明
